### post request -- new users/user registration
post http://localhost:4000/usersapi/register
Content-Type: application/json

{
    "username":"Bharath",
    "password":"Bharath",
    "status":true,
    "email": "bharath@gmail.com",
    "inventory":[
        {"Paracetmol":500},
        {"Citrozen":400}
    ]
}

###
get http://localhost:4000/usersapi/inventory/Bharath

### put request -- update user details
put http://localhost:4000/usersapi/update-inventory
Content-Type: application/json

{
    "username":"Satya",
    "inventory":[
        {"Gel":100},
        {"Vitamin C":20}
    ]
}

//----------------------------------------------------------------------
### login request /user login
post http://localhost:4000/usersapi/login
Content-Type: application/json

{
    "username":"BSP",
    "password":"BSP"
}
